CREATE TABLE users(user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(40),login varchar(40) NOT NULL, name varchar(40) NOT NULL, birthday date);

CREATE TABLE friends(friends_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id INTEGER REFERENCES users(user_id),
    other_user_id INTEGER REFERENCES users(user_id), friends_status BOOLEAN);

CREATE TABLE film(film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40), description varchar(40), release_date date, duration LONG, rating_id INTEGER REFERENCES rating(rating_id));

CREATE TABLE popular_film(popular_film INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER REFERENCES film(film_id), user_id INTEGER REFERENCES users(user_id));

CREATE TABLE rating(rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(40));

CREATE TABLE film_genre(film_genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER REFERENCES film(film_id), name varchar(40));

