CREATE TABLE IF NOT EXISTS users(user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 email varchar(40),login varchar(40) NOT NULL, name varchar(40) NOT NULL, birthday date);

CREATE TABLE IF NOT EXISTS friendship(friends_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id INTEGER REFERENCES users(user_id),
                                      other_user_id INTEGER REFERENCES users(user_id), friends_status BOOLEAN);

CREATE TABLE IF NOT EXISTS mpa(mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(40));

CREATE TABLE IF NOT EXISTS film(film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name varchar(40), description varchar(40), release_date date, duration LONG, mpa_id INTEGER REFERENCES mpa(mpa_id));

CREATE TABLE IF NOT EXISTS film_likes(popular_film INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      film_id INTEGER REFERENCES film(film_id), user_id INTEGER REFERENCES users(user_id));

CREATE TABLE IF NOT EXISTS genre(genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 genre_name varchar(40));

CREATE TABLE IF NOT EXISTS genre_film(genre_film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      film_id INTEGER REFERENCES film(film_id),
                                      genre_id INTEGER REFERENCES genre(genre_id));


delete from FILM_LIKES where film_likes.popular_film > 0;
ALTER TABLE FILM_LIKES ALTER COLUMN popular_film RESTART WITH 1;
DELETE FROM FRIENDSHIP where FRIENDS_ID > 0;
DELETE FROM USERS where USER_ID > 0;
ALTER TABLE USERS ALTER COLUMN user_id RESTART WITH 1;
ALTER TABLE FRIENDSHIP ALTER COLUMN friends_id RESTART WITH 1;
DELETE FROM genre_film where genre_id > 0;
DELETE FROM FILM where FILM_ID > -1;
ALTER TABLE FILM ALTER COLUMN film_id RESTART WITH 1;
delete from GENRE where genre_id > 0;
ALTER table genre ALTER COLUMN genre_id RESTART WITH 1;
DELETE FROM MPA where MPA.MPA_ID > 0;
ALTER TABLE MPA ALTER COLUMN MPA_ID RESTART WITH 1;
insert into genre (genre_name) values ('Комедия'), ('Драма'), ('Мультфильм') , ('Триллер') , ('Документальный'), ('Боевик');
insert into mpa (name) values ('G'), ('PG'), ('PG-13') , ('R') , ('NC-17');

